finish commit
sergeynakul/garage_library pull request #1
Opened 2020-06-10 13:50 UTC by sergeynakul

2020-06-10 14:00 UTC, KonstantinFaleev approved these changes
Ok!

2020-06-10 14:29 UTC, derunva approved these changes
Nice!

2020-06-16 16:56 UTC, epoberezhny requested changes

2020-06-16 16:56 UTC, epoberezhny commented on db/seed.rb
> +module Seed
Make it a separate class please

2020-06-16 16:56 UTC, epoberezhny commented on moduls/validation.rb
> +    def validate_positive(value, name)
Consider using of validation of type "greatest or equal"

2020-06-16 16:56 UTC, epoberezhny commented on models/author.rb
> +class Author
Maybe we should add some getters?

2020-06-16 16:56 UTC, epoberezhny commented on models/book.rb
> +  attr_reader :title
reader for author?

2020-06-16 16:56 UTC, epoberezhny commented on models/library.rb
> +  attr_accessor :authors, :books, :readers, :orders
attr_reader

2020-06-16 16:56 UTC, epoberezhny commented on models/library.rb
> +  def number_readers_of_top_books
Should have an argument

2020-06-16 16:56 UTC, epoberezhny commented on models/library.rb
> +    @orders.group_by(&entity).max_by(quantity) { |_, value| value.length }.to_h.keys
map(&:first)

2020-06-16 16:56 UTC, epoberezhny commented on models/library.rb
> +    @orders.select { |order| top_books(BOOK_QUANTITY).include? order.book }.map(&:reader).uniq.length
```ruby
popular_books = top_books(BOOK_QUANTITY)
@orders.select { |order| popular_books.include? order.book }.map(&:reader).uniq.length
```

2020-06-20 10:52 UTC, sergeynakul commented on moduls/validation.rb
> +    def validate_positive(value, name)
remind, please what did you mean? I must rename method validate_positive?

2020-06-23 17:46 UTC, epoberezhny commented
Add ruby version please

2020-06-23 17:46 UTC, epoberezhny requested changes

2020-06-23 17:46 UTC, epoberezhny commented on models/library.rb
> +  attr_reader :authors, :books, :readers, :orders
Remove it please

2020-06-23 17:46 UTC, epoberezhny commented on db/seed.rb
> +  class << self
Make it a 'classic' class

2020-06-25 09:55 UTC, artem247 commented on index.rb
> +library.load_data
It seems like seeded data is never assigned back to the original library on which statistics calculations are performed

2020-06-29 21:07 UTC, epoberezhny requested changes

2020-06-29 21:07 UTC, epoberezhny commented on index.rb
> +library.load_data
What do you mean?

2020-06-29 21:07 UTC, epoberezhny commented on models/library.rb
> +  attr_reader :authors, :books, :readers, :orders
What about this?

2020-06-30 06:12 UTC, sergeynakul commented on index.rb
> +library.load_data
1. library = Library.new - create instance of Library with @authors = [ ], @books = [ ], @readers = [ ], @orders = [ ]
2. seed = Seed.new(library) - create instance of Seed
3. seed.generate_data - fill library @authors, @books, @readers, @orders with faker data
4. library.store_data - save library data in yaml file
5. library.load_data - read library data from yaml file

2020-06-30 08:38 UTC, epoberezhny commented on index.rb
> +library.load_data
Ok. But you can create a new instance of library and load data

2020-06-30 17:30 UTC, epoberezhny approved these changes

2020-09-01 19:31 UTC, merged